name: attendly
description: ATTENDLY Smart Attendance System — A modern Flutter attendance app for Android.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # QR Code Generation
  qr_flutter: ^4.1.0

  # QR Code Scanning via device camera
  mobile_scanner: ^5.2.3

  # State management
  provider: ^6.1.2

  # Date/time formatting
  intl: ^0.19.0

  # Local storage — remember student device login
  shared_preferences: ^2.2.2

  # File path resolution — QR save to Pictures
  path_provider: ^2.1.2
  gal: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Launcher icon generator
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"
  web:
    generate: false

flutter:
  uses-material-design: true

  assets:
    - assets/data/mock/students.json
    - assets/data/mock/teachers.json
    - assets/data/mock/sessions.json
    - assets/data/mock/attendance.json
    - assets/icon/icon.png
