import 'dart:convert';

/// Represents a class attendance session generated by a teacher.
///
/// PRODUCTION NOTE: Session validation must also occur server-side.
/// The QR payload should be signed/verified to prevent tampering.
class AttendanceSession {
  final String id;
  final String teacherId;
  final DateTime createdAt;
  final DateTime expiresAt;

  /// Mutable status: 'active', 'ended', 'expired'
  String status;

  AttendanceSession({
    required this.id,
    required this.teacherId,
    required this.createdAt,
    required this.expiresAt,
    required this.status,
  });

  /// True only when status == 'active' AND current time is before expiresAt.
  bool get isActive =>
      status == 'active' && DateTime.now().isBefore(expiresAt);

  bool get isEnded => status == 'ended';

  /// True when marked active but time has passed expiresAt.
  bool get isExpiredByTime =>
      status == 'active' && DateTime.now().isAfter(expiresAt);

  factory AttendanceSession.fromJson(Map<String, dynamic> json) {
    return AttendanceSession(
      id: json['id'] as String,
      teacherId: json['teacherId'] as String,
      createdAt: DateTime.parse(json['createdAt'] as String),
      expiresAt: DateTime.parse(json['expiresAt'] as String),
      status: json['status'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'teacherId': teacherId,
      'createdAt': createdAt.toIso8601String(),
      'expiresAt': expiresAt.toIso8601String(),
      'status': status,
    };
  }

  /// Generates the JSON string to be encoded as a QR code.
  ///
  /// PRODUCTION NOTE: This payload should be signed with a server secret.
  String toQrPayload() {
    return jsonEncode({
      'type': 'attendance_session',
      'sessionId': id,
      'teacherId': teacherId,
      'createdAt': createdAt.toIso8601String(),
      'expiresAt': expiresAt.toIso8601String(),
      'status': status,
    });
  }

  @override
  bool operator ==(Object other) =>
      other is AttendanceSession && other.id == id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() => 'AttendanceSession($id, status=$status)';
}
